export const CustomerDataList=[
    {
        id: '',
        fullName: 'Sujal Tamang',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'GYM',
        subscriptionType: 'Monthly',
        shift: 'Morning',
        credit: '3000',
        startDate:'',
        expireOn: '9/1/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:false,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      
            document:'',
          },
      },
      {
        id: '',
        fullName: 'Ram Adhikari',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'Cardio',
        subscriptionType: 'Monthly',
        shift: 'Morning',
        credit: '00',
        startDate:'',
        expireOn: '9/21/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:null,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      
        document:'',
      },

      },
      {
        id: '',
        fullName: 'Sujal Tamang',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'Boxing',
        subscriptionType: 'Monthly',
        shift: 'Morning',
        credit: '200',
        startDate:'',
        expireOn: '9/11/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:null,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      
        document:'',
      },
      },
      {
        id: '',
        fullName: 'Laban Rai',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'GYM',
        subscriptionType: 'Yearly',
        shift: 'Evening',
        credit: '00',
        startDate:'',
        expireOn: '9/15/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:null,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      

        document:'',
      },
      },
      {
        id: '',
        fullName: 'Sujal Tamang',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'Boxing',
        subscriptionType: 'Monthly',
        shift: 'Morning',
        credit: '200',
        startDate:'',
        expireOn: '9/7/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:null,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      

        document:'',
      },
      },
      {
        id: '',
        fullName: 'Sujal Tamang',
        email:'',
        gender:'',
        bloodGroup:'',
        address:'',
        healthStatus:'',
        program: 'Boxing',
        subscriptionType: 'Monthly',
        shift: 'Morning',
        credit: '200',
        startDate:'',
        expireOn: '9/24/2022',
        phoneNumber:'',
        planPrice:'',
        pay:'',
        duePayment:'',
        assignBy:'',
        profileImg:'',
        status:true,
        freeze:null,
        emergencyContact:{
          fullName:'',
          contactNumber:'',
          optContactNumber:'',
          relationship:''
        },
        physicalDetail:{
          weight:null,
          neck:null,
          shoulder:null,
          forearm:null,
          arm:null,
          wrist:null,
          chest:null,
          waist:null,
          hip:null,
          thigh:null,
          calf:null,
      
        
        document:'',
      },
      },
      ];